
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdsndurnfagupfohuefb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kc25kdXJuZmFndXBmb2h1ZWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDE2NzQsImV4cCI6MjA2MTE3NzY3NH0.jXcmznLhHpy4oFCBF67xJTmKh4wYDAkMD97zy40e-zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);
